schema = 3

[mod]
  [mod."github.com/jackpal/go-nat-pmp"]
    version = "v1.0.2"
    hash = "sha256-L1D4Yoxnzihs795GZ+Q3AZsFP5c4iqyjTeyrudzPXtw="
  [mod."github.com/pborzenkov/go-transmission"]
    version = "v0.3.0"
    hash = "sha256-H322j/K6hOILzqfcX7qw0ENBVAwo84oQk8AggdkXjVw="
